version: "3.4"

x-common-variables: &common-variables
  MYSQL_DATABASE: situation

services:
  mysql:
    image: mysql:5.7
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./db/initial.sql:/docker-entrypoint-initdb.d/initial.sql
  server:
    build: ./server
    depends_on:
      - mysql
    expose:
      - 5000
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
    links:
      - mysql
    command: npm run start
  client:
    build: ./client
    depends_on:
      - mysql
      - server
    environment:
      <<: *common-variables
      NODE_PATH: src
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    links:
      - server
    command: npm run start