version: "3.7"
services:
  mysql:
    container_name: mysql
    build:
      context: ./mysql
    networks:
      - internal
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: situation 
  api:
    container_name: api
    build:
      context: ./api
    depends_on:
      - mysql
    networks:
      - internal
  app:
    container_name: app
    build:
      context: ./app
    networks:
      - internal
    depends_on:
      - mysql
      - api
  

networks:
  internal:
    driver: bridge

volumes:
  mysql_data: